# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Guido Formichi
tagline: 'Linguist'
description: "PhD student of Theoretical and Experimental Linguistics at <a href='https://www.iusspavia.it/it/rubrica/guido-formichi' target='_blank'>IUSS</a> Pavia, Italy."
url: https://guidoformichi.github.io/
baseurl: ""

author:
  name: 'Mark Otto'
  url: https://twitter.com/mdo

paginate: 5

# Custom vars
# version: 2.1.0

# github:
#   repo: https://github.com/poole/hyde
