# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Guido Formichi
tagline: 'Linguist'
description: 'I'm a linguist at <a href="https://www.iusspavia.it/it/rubrica/guido-formichi" target="_blank">iuss</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url: https://blablacarro.github.io
baseurl: ""

author:
  name: 'Mark Otto'
  url: https://twitter.com/mdo

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/poole/hyde
